# the name of our job
name: test

# yes, we want to run for all branches and pull requests
on:
  workflow_dispatch:

# we have just our job `test`
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Set up Helm 
      uses: azure/setup-helm@v2.1
      with:
        version: v3.8.1

    - name: test 
      run: |
        ls -la 
        helm plugin install https://github.com/halkeye/helm-repo-html

    - name: test2
      run: |
        helm repo-html
        ls -la 
